name: test

on:
    push:
        branches:
            - main

    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.platform }}
        strategy:
            matrix:
                platform: [ ubuntu-latest, macos-latest, windows-latest ]
                python-version: [ '3.7', '3.8', '3.9' ]

        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}

            -   uses: ibnesayeed/setup-ipfs@master
                with:
                    ipfs_version: 0.19.2

            -   name: install deps
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install tox-gh-actions

            -   name: tox
                run: tox
                env:
                    PYTHON_VER: ${{ matrix.python-version }}
                    PLATFORM: ${{ matrix.platform }}

    check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toxenv: [ styleck, typeck, py3-httpx ]

        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-python@v4
                with:
                    python-version: '3.9'

            -   name: install deps
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install tox tox-gh-actions

            -   name: tox
                run: tox
                env:
                    TOXENV: ${{ matrix.toxenv }}
